// import { Layout } from "../components/Layout"
import ThemeClient from "../components/ThemeClient"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ThemeClient>
        {/* <Layout> */}
          {children}
        {/* </Layout> */}
      </ThemeClient>
      </body>
    </html>
  )
}
